// Top-level build file where you can add configuration options common to all sub-projects/modules.

apply from: "config.gradle"

buildscript {
    // 在 buildscript 内部 apply，确保下面可以使用 versions 变量
    apply from: "config.gradle"
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // 使用 gradle 8.1.2 和 kotlin 1.9.21
        classpath 'com.android.tools.build:gradle:8.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21"
    }
}

// 给所有的项目配置
allprojects {

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
