apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'

android {
    namespace 'com.xxd.common'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        //开启MultiDex分包方法
        multiDexEnabled true

        kapt {
            arguments {
                // 阿里路由的包参数
                arg("AROUTER_MODULE_NAME", project.getName())
            }
        }

        // 资源前置限定，只报红，编译可以通过
        resourcePrefix "${project.name}_"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        aidl true
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        // 解决ktx的编译问题，默认使用的是1.6
        jvmTarget = "1.8"
    }
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])

        // Android 必须的库
        api libs.androidx.appcompat
        // api 'com.android.support:appcompat-v7:28.0.0' // 建议移除旧的 support 库，与 androidx 冲突

        // kotlin相关
        api libs.kotlin.stdlib
        api libs.kotlin.reflect
        api libs.kotlin.coroutines.core
        api libs.kotlin.coroutines.android

        // ktx & lifecycle
        api libs.androidx.core.ktx
        api libs.androidx.fragment.ktx
        api libs.bundles.lifecycle
        api libs.androidx.lifecycle.runtime.compose

        // 常用工具
        api libs.androidx.multidex
        api libs.logger
        api libs.rxpermissions
        api libs.arouter.api
        api libs.immersionbar
        api libs.immersionbar.components
        api libs.immersionbar.ktx
        api libs.rxTool.kit
        api libs.jackson.core
        api libs.jackson.databind
        api libs.gson
        api libs.moshi
        api libs.rxjava
        api libs.rxandroid
        api libs.okio
        api libs.okhttp
        api libs.retrofit
        api libs.retrofit.converter.gson
        api libs.glide
        api libs.room.runtime

        // navigation
        api libs.androidx.navigation.fragment
        api libs.androidx.navigation.ui
        api libs.androidx.navigation.compose
        api libs.androidx.navigation.fragment.ktx
        api libs.androidx.navigation.ui.ktx
        api libs.androidx.navigation.dynamic.features.fragment

        // 系统控件
        api libs.androidx.constraintlayout
        api libs.androidx.recyclerview
        api libs.androidx.cardview
        api libs.androidx.viewpager2
        api libs.flexbox
        api libs.material

        // 第三方控件
        api libs.brvah
        api libs.banner
        api libs.magicIndicator
        api libs.refresh.layout.kernel
        api libs.refresh.header.classics

        testImplementation libs.junit
        androidTestImplementation libs.androidx.test.ext.junit
        androidTestImplementation libs.androidx.test.espresso.core
    }
    sourceSets {
        main {
            aidl {
                srcDirs 'src\\main\\aidl'
            }
        }
    }
}
